<?php

namespace Database\Seeders;

use App\Models\employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Inserta empleados con datos aleatorios
        employee::create(['document' => 1005869928, 'name' => 'FREYDE SINISTERRA ANA MICHEL', 'position' => 'ANALISTA DE DATOS', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1005875426, 'name' => 'LONDOÑO ANGULO MAIRYNG TAMARA', 'position' => 'AUXILIAR COMERCIAL MARKETING DIGITAL', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1005969129, 'name' => 'ROMERO CARMONA LINA MARCELA', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1006186252, 'name' => 'TELLO SERNA MELQUISEDEC', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1662483, 'area_id' => 8]);
        employee::create(['document' => 1006189251, 'name' => 'VALENCIA PEÑA HAMYR DAVID', 'position' => 'COMMUNITY MANAGER', 'salary' => 1673295, 'area_id' => 3]);
        employee::create(['document' => 1006189928, 'name' => 'TORRES MINA DIANA LIZETH', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1006190412, 'name' => 'VALDES VILLEGAS LINA MARCELA', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1006192001, 'name' => 'CAICEDO ARROYO DOLEISA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1006194078, 'name' => 'CANDELO BANGUERA MARYURI CIRLEY', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1006194292, 'name' => 'LOPEZ MORENO HORACIO', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1006194836, 'name' => 'MONTAÑO CUERO MONICA ANDREA', 'position' => 'ASISTENTE DE OPERACIONES', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 1006195054, 'name' => 'VERGARA RIASCOS JEYSON', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1006197163, 'name' => 'SINISTERRA TOBAR LEIDY TAMARA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1006197900, 'name' => 'LARA ZORRILLA JOSELIN', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1006198307, 'name' => 'BONILLA GAMBOA ADRIANA CAROLINA', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1006198459, 'name' => 'MURIEL OBREGON HECTOR MARIO', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1006200699, 'name' => 'RIASCOS PINEDA NILSON STIWAR', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1006201395, 'name' => 'PANDALES PANDALES RONEY', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1006202292, 'name' => 'NUÑEZ ORTIZ YAREN YASURY', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1006203280, 'name' => 'ALEGRIA MOSQUERA WENDY JULIETH', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1006427448, 'name' => 'ARBELAEZ GONZALEZ JORGE LUIS', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1007362740, 'name' => 'RIASCOS RIASCOS MARIA IRMA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1007527271, 'name' => 'DIAZ DIAZ JOAN SEBASTIAN', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1007758234, 'name' => 'MONTAÑO ANGULO KAREN JOHANNA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1007763407, 'name' => 'DIAZ SAA THAIS MICHEL', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1007784125, 'name' => 'MURILLO MEDINA LINA MARCELA', 'position' => 'LIDER DE PRODUCTOS', 'salary' => 1700000, 'area_id' => 3]);
        employee::create(['document' => 1007838821, 'name' => 'HURTADO MOSQUERA JOSE TOMAS', 'position' => 'AUXILIAR GESTION HUMANA', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1007850869, 'name' => 'ARRECHEA CUERO JUAN DAVID', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1007907860, 'name' => 'BLANDON GRUESO LEIDI KATERINE', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1010154196, 'name' => 'RIASCOS RIASCOS KELLY TATIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1010207631, 'name' => 'ALVAREZ CASARRUBIA KEYDIS', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1013679057, 'name' => 'CASTILLO VENTE MAURO STIVEN', 'position' => 'WEB MASTER', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1028161800, 'name' => 'ZUÑIGA SINISTERRA JAIDER', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1028181072, 'name' => 'ARIAS ASPRILLA PAOLA ANDREA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1030682110, 'name' => 'BERMUDEZ QUIÑONEZ LAURA BOLENA', 'position' => 'COORDINADOR DE COMUNICACIONES', 'salary' => 2513440, 'area_id' => 3]);
        employee::create(['document' => 1053770603, 'name' => 'CUERO QUIÑONEZ ANDRES ARMANDO', 'position' => 'ADMINISTRADOR DE ZONA', 'salary' => 2513440, 'area_id' => 3]);
        employee::create(['document' => 1067871104, 'name' => 'SANCHEZ ESPITIA EVER NICOLAS', 'position' => 'DIRECTOR COMERCIAL', 'salary' => 5504973, 'area_id' => 3]);
        employee::create(['document' => 1085278175, 'name' => 'LOPEZ MIRANDA NELCY AMPARO', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1087126762, 'name' => 'CAICEDO LANDAZURY TARCILA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1087674263, 'name' => 'CORAL JIMENEZ ELSY YANIRA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1094906544, 'name' => 'MORENO MORENO OSCAR ANDRES', 'position' => 'COORDINADOR DE PRODUCTO', 'salary' => 2513440, 'area_id' => 3]);
        employee::create(['document' => 1107086352, 'name' => 'RODRIGUEZ MOSQUERA DANIEL', 'position' => 'ANALISTA DE OPERACIONES', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 1110262319, 'name' => 'CARDOSO DAVILA SIRLADIZ', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1111738641, 'name' => 'RAMOS RENTERIA MARLON', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111739200, 'name' => 'ESTRADA MANCILLA MARGARITA', 'position' => 'ANALISTA DE NOMINA', 'salary' => 1967040, 'area_id' => 4]);
        employee::create(['document' => 1111740856, 'name' => 'ARIAS TABARES JHON EDWIN', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111741621, 'name' => 'LARGO VALENZUELA EDIRLEY', 'position' => 'AUXILIAR DE MERCADEO', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111741914, 'name' => 'VENTE VALENCIA JANNELLY', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111745046, 'name' => 'ARDILA RIASCOS YEISA LIDA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111745687, 'name' => 'HUILA MUÑOZ ANGEL FERNANDO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111747706, 'name' => 'CARDENAS TORRES JOHAN ANDRES', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111749529, 'name' => 'CASTILLO SAAVEDRA JESUS JULIAN', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1111749930, 'name' => 'CAMPAZ RIVAS AYDA LUISA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111752942, 'name' => 'RIASCOS RIASCOS DERLIS', 'position' => 'AUXILIAR ADMINISTRATIVO', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111753359, 'name' => 'BENITEZ ARISMENDI EYNER', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1111755029, 'name' => 'MICOLTA ALOMIA MARTHA LILIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111757805, 'name' => 'MURILLO MORENO EDWIN ANDRES', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1536194, 'area_id' => 1]);
        employee::create(['document' => 1111760486, 'name' => 'MONTAÑO HURTADO JAMES', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111761541, 'name' => 'CAICEDO CONGOLINO ANTHONY', 'position' => 'OPERADOR DE MEDIOS TECNOLOGICOS', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111761547, 'name' => 'PRETEL MOSQUERA CINTHYA VANESSA', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111761982, 'name' => 'CAMACHO VELLAISAC BRAYAN STIVEN', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111763413, 'name' => 'OROBIO GAMBOA YUSEYDY YHOANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111766165, 'name' => 'DIAZ VILLOTA EDWIN ANDRES', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1111772079, 'name' => 'SAAVEDRA RUIZ ERWIN', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111773295, 'name' => 'GAMBOA ASPRILLA JHAN CARLOS', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1111773334, 'name' => 'CAMPAZ RODRIGUEZ HERNAN', 'position' => 'AUXILIAR ELECTRICO', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111775080, 'name' => 'LARA ESTUPIÑAN LINA FERNANDA', 'position' => 'COORDINADORA DE TALENTO HUMANO', 'salary' => 2602292, 'area_id' => 4]);
        employee::create(['document' => 1111775930, 'name' => 'ZUÑIGA SINISTERRA FERNEY', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111776881, 'name' => 'MONTAÑO SANCHEZ MARLON SAMIR', 'position' => 'AUXILIAR TECNICO DE INFRAESTRUCTURA ( REDES)', 'salary' => 2039689, 'area_id' => 1]);
        employee::create(['document' => 1111784099, 'name' => 'GARCES RIASCOS FRANCISCO', 'position' => 'VIGILANTE', 'salary' => 1160000, 'area_id' => 2]);
        employee::create(['document' => 1111785076, 'name' => 'VIDAL VALENCIA EDITH', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111786212, 'name' => 'PERLAZA PAYAN CINDY PAMELA', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111786216, 'name' => 'VIVEROS VALENCIA JHONNY', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1111786366, 'name' => 'ZAMORA OCAMPO YALI TATIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111787065, 'name' => 'URRUTIA MURILLO NELSY YAJAIRA', 'position' => 'COORDINADOR DE SOPORTE TECNICO', 'salary' => 2096553, 'area_id' => 1]);
        employee::create(['document' => 1111788224, 'name' => 'OBONAGA GAMBOA ANGELA SHARON', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111788642, 'name' => 'RIASCOS JARAMILLO JORGE ISAAC', 'position' => 'SUPERVISOR DE MANTENIMIENTO DE INFRAESTRUCTURA FIS', 'salary' => 1901472, 'area_id' => 8]);
        employee::create(['document' => 1111788916, 'name' => 'MORENO VALENCIA HAMLETH', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111788975, 'name' => 'PAREDES TORRES ANA SOFIA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111789365, 'name' => 'CABEZAS SANCHEZ MARIA JOSE', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111789779, 'name' => 'ZAMORA PERLAZA WALTER', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111789938, 'name' => 'BERMUDEZ VIVEROS JAILIN MICHEL', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111790394, 'name' => 'BENAVIDES RODRIGUEZ KATHERINE', 'position' => 'IMPULSADOR BETPLAY', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111791893, 'name' => 'JIMENEZ ROMERO HELMER ADOLFO', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1483410, 'area_id' => 1]);
        employee::create(['document' => 1111792293, 'name' => 'PINO DUQUE EDWARD ALFONSO', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1111792394, 'name' => 'PLACIDES MURILLO ORLAY', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 1111792505, 'name' => 'TORRES CUERO EIDER ALFREDO', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111792794, 'name' => 'HERNANDEZ ACHITO LINA MARCELA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111794854, 'name' => 'ARRECHEA SINISTERRA DIANA MARCELA', 'position' => 'ANALISTA DE OPERACIONES', 'salary' => 1394413, 'area_id' => 1]);
        employee::create(['document' => 1111795209, 'name' => 'RAMIREZ SINISTERRA KAREN VANESSA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111798455, 'name' => 'VALENCIA RENTERIA JOE STWART', 'position' => 'COORDINADOR DE DESARROLLO DE SOFTWARE', 'salary' => 2841280, 'area_id' => 1]);
        employee::create(['document' => 1111798825, 'name' => 'SAA CUERO ANDRES FELIPE', 'position' => 'COORDINADOR DE APLICACIONES', 'salary' => 2155002, 'area_id' => 1]);
        employee::create(['document' => 1111800701, 'name' => 'CONTRERAS RUSELL CHRISTIAN FERNANDO', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111801062, 'name' => 'AGUDELO HOLGUIN NELLY YOLIETH', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1160000, 'area_id' => 3]);
        employee::create(['document' => 1111804773, 'name' => 'BUENAVENTURA ALEGRIA LUIS ENRIQUE', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 1111805696, 'name' => 'MOSQUERA BANGUERA JOHANN DAVID', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1483410, 'area_id' => 1]);
        employee::create(['document' => 1111805724, 'name' => 'MINA FERRIN MELISSA ANDREA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111805812, 'name' => 'RUIZ ROSENDO MARIANA', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111806263, 'name' => 'ALEGRIA ESCOBAR DIANA PATRICIA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111809651, 'name' => 'RIASCOS QUIÑONES YENIFER', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111809792, 'name' => 'RODAS GOMEZ NATHALY', 'position' => 'AUXILIAR DE SISTEMA DE GESTION  SST', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1111810559, 'name' => 'RENTERIA ARROYO PABLO JOHAN', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1631751, 'area_id' => 1]);
        employee::create(['document' => 1111813091, 'name' => 'MEDINA ANGULO INGRI TATIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111813765, 'name' => 'CAICEDO HURTADO RONALDO', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1111815514, 'name' => 'CACERES VALENCIA ERIC FERNANDO', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1111816046, 'name' => 'GONZALEZ VALENCIA JUAN PABLO', 'position' => 'ANALISTA DE OPERACIONES', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 1111816154, 'name' => 'RIASCOS RENTERIA MARIA DOLORES', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111816403, 'name' => 'VALENCIA VIVEROS YELIN MICHEL', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111817435, 'name' => 'APONTE TORRES LINA MELISSA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1111818397, 'name' => 'PARRA TORRES JIMMY FERNANDO', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 1111818702, 'name' => 'HERNANDEZ ZAPATA MIGUEL ANGEL', 'position' => 'AUXILIAR ADMINISTRATIVO', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1112227225, 'name' => 'TORRES MONTAÑO RUBY SIRLEY', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1113362397, 'name' => 'DELGADO JHEIDER ALEXIS', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1113362554, 'name' => 'LOPEZ GERALDINE', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1113362603, 'name' => 'RIASCOS ANGULO LUZ ALBA', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1114731308, 'name' => 'DOMINGUEZ ARBOLEDA JOHN FREDDY', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1114735149, 'name' => 'VALLECILLA RENTERIA REINA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1114735176, 'name' => 'GARCES NUÑEZ FRANKY EDUARDO', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1115450045, 'name' => 'GARCES ANGULO EDWIN DUVAN', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1118539341, 'name' => 'BALLESTEROS SALDARRIAGA HELMER ALBERTO', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1160000, 'area_id' => 1]);
        employee::create(['document' => 1130622846, 'name' => 'VALENCIA ARROYAVE FRANK ROBEIROT', 'position' => 'JEFE DE MERCADEO Y VENTAS', 'salary' => 3400000, 'area_id' => 3]);
        employee::create(['document' => 1143836608, 'name' => 'MURILLO KLINGER CARLOS FERNANDO', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1144037421, 'name' => 'ALDANA CUERO ANGELA VIVIANA', 'position' => 'AUXILIAR ADMINISTRATIVO DE GESTION HUMANA', 'salary' => 1521178, 'area_id' => 4]);
        employee::create(['document' => 1144097989, 'name' => 'CASTRO ALVARADO LAURA MARCELA', 'position' => 'APRENDIZ - UNIVERSITARIO', 'salary' => 1160000, 'area_id' => 4]);
        employee::create(['document' => 1144129881, 'name' => 'MORA MINA AGUSTIN', 'position' => 'ESCOLTA', 'salary' => 2535296, 'area_id' => 2]);
        employee::create(['document' => 1144161965, 'name' => 'TIGREROS SALAZAR JONATAN', 'position' => 'ESCOLTA', 'salary' => 2320000, 'area_id' => 2]);
        employee::create(['document' => 1148445328, 'name' => 'REYES RAMOS KAREN YULIETH', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1148445411, 'name' => 'ADVINCOLA ANGULO WILMER', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1151196399, 'name' => 'ALOMIA MIRANDA ASTRID LORENA', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1151440702, 'name' => 'FIGUEROA HURTADO ALEXANDER', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1151443486, 'name' => 'LOANGO ROJAS HELLEN GIZETH', 'position' => 'ASISTENTE DE SISTEMAS', 'salary' => 1425455, 'area_id' => 1]);
        employee::create(['document' => 1151950139, 'name' => 'GOMEZ MUÑOZ JOHAN MIGUEL', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1192738711, 'name' => 'RODRIGUEZ MORALES LOREN CAMILA', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1192909689, 'name' => 'TAPIA DAVILA MABY GISSETH', 'position' => 'AUXILIAR ADMINISTRATIVO', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1192917786, 'name' => 'GONZALEZ ANCHICO ANGIE GERALDINE', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1192918158, 'name' => 'PUENTES RIASCOS YONI STIVEN', 'position' => 'AUXILIAR DE MANTENIMIENTO DE INFRAESTRUCTURAS FISI', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 1192918324, 'name' => 'ARAGON BALLESTEROS NATALIA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1193220129, 'name' => 'CAMBINDO ORDOÑEZ LUISA YAJAIRA', 'position' => 'AUXILIAR DE ENTRENAMIENTO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 1193220130, 'name' => 'MANTILLA SINISTERRA KELLY MELISSA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 1235138941, 'name' => 'RODRIGUEZ OBREGON JUAN DIEGO', 'position' => 'AUXILIAR DE SGC Y SERVICIO AL CLIENTE', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1235139601, 'name' => 'HURTADO CASTRILLON ANDRES FELIPE', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 1292738711, 'name' => 'RODRIGUEZ MORALES LOREN CAMILA', 'position' => 'ASESORES DE VENTA', 'salary' => 1160000, 'area_id' => 3]);
        employee::create(['document' => 13105290, 'name' => 'MICOLTA RIASCOS MARCOS', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 1415560, 'name' => 'BRITO MUJICA JANSON ENRIQUE', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 14470265, 'name' => 'RIASCOS CAMACHO CELESTINO', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 14471164, 'name' => 'PRECIADO CAICEDO JOHN JAIRO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 14471894, 'name' => 'CAICEDO VENTE MANUEL', 'position' => 'OPERADOR DE MEDIOS TECNOLOGICOS', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 14473448, 'name' => 'ISAZA BUENO EDINSON', 'position' => 'SUPERVISOR DE MEDIOS TECNOLOGICOS', 'salary' => 1647942, 'area_id' => 2]);
        employee::create(['document' => 14473836, 'name' => 'RIVAS ARBOLEDA RICHARD ALEXANDER', 'position' => 'COORDINADOR DE INFRAESTRUCTURA', 'salary' => 2741861, 'area_id' => 1]);
        employee::create(['document' => 14474330, 'name' => 'SABANERO JOHN JAIRO', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 14576186, 'name' => 'SALCEDO NARVAEZ MARINO', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 14888663, 'name' => 'MORALES BERMUDEZ FRANCISCO JAVIER', 'position' => 'DIRECTOR DE TIC', 'salary' => 6084710, 'area_id' => 1]);
        employee::create(['document' => 16468619, 'name' => 'ANGULO ANGULO GUSTAVO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16477758, 'name' => 'ANGULO HUGO MARINO', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 16483590, 'name' => 'VALENCIA ORTIZ FELIX JESUS', 'position' => 'AUXILIAR DE LOGISTICA', 'salary' => 1536194, 'area_id' => 8]);
        employee::create(['document' => 16486583, 'name' => 'LANDAZURI GONZALEZ WILSON', 'position' => 'MENSAJERO CONDUCTOR', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 16493989, 'name' => 'GUEVARA CAMACHO JAIME ARNULFO', 'position' => 'OPERADOR DE MEDIOS TECNOLOGICOS', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16494219, 'name' => 'SARRIA RODALLEGA MARIO JOSE', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1588645, 'area_id' => 1]);
        employee::create(['document' => 16495824, 'name' => 'CASTILLO SALAZAR JOSE SEGUNDO', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16502191, 'name' => 'RIASCOS RIASCOS NICANOR', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16502475, 'name' => 'MANYOMA LOZANO HEILER', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16502850, 'name' => 'HENAO CASTAÑO JHOANNY', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16505577, 'name' => 'RIASCOS SUAREZ AVELINO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16507838, 'name' => 'RIASCOS ARAGON WILSON', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 16779417, 'name' => 'GALINDEZ HERMINSUL', 'position' => 'ESCOLTA', 'salary' => 2962653, 'area_id' => 2]);
        employee::create(['document' => 16782900, 'name' => 'BENITEZ GRAJALES CARLOS HUMBERTO', 'position' => 'JEFE DE SEGURIDAD', 'salary' => 4460176, 'area_id' => 2]);
        employee::create(['document' => 16832522, 'name' => 'PAZ NARVAEZ ADRIAN GIOVANNI', 'position' => 'ESCOLTA', 'salary' => 1929536, 'area_id' => 2]);
        employee::create(['document' => 16858387, 'name' => 'OSSA DOMINGUEZ GILBERTO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16945301, 'name' => 'SERNA CABRERA JAIR', 'position' => 'ESCOLTA', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 16945783, 'name' => 'BARONA ANGULO HARVEY', 'position' => 'COORDINADOR DE NUEVOS CANALES', 'salary' => 2843203, 'area_id' => 3]);
        employee::create(['document' => 16946539, 'name' => 'FARRUFIA RIASCOS FRANK EDWIN', 'position' => 'COORDINADOR DE BASES DE DATOS', 'salary' => 4371200, 'area_id' => 1]);
        employee::create(['document' => 16948297, 'name' => 'QUIÑONES CAICEDO JUAN CARLOS', 'position' => 'AUXILIAR OBRAS CIVILES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 25498348, 'name' => 'DIAGO MINA FRANCISCA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 29104960, 'name' => 'CORTES TORRES DORIS JUSTINA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 29229140, 'name' => 'BONILLA VENTE SANDRA PATRICIA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 29233892, 'name' => 'MOSQUERA CANGA DIANA CAROLINA', 'position' => 'ASESORES DE VENTA', 'salary' => 1160000, 'area_id' => 3]);
        employee::create(['document' => 29398129, 'name' => 'ENRIQUEZ IJAJI MARIA DEL ROSARIO', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 29844821, 'name' => 'ZAPATA MUÑOZ CLAUDIA NORY', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 31588106, 'name' => 'ORTIZ CAMPAZ ROSARIO', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 31600944, 'name' => 'CAMACHO BELLAIZAC ELVIA MARIA', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 31602170, 'name' => 'SOLIS SANCHEZ MARINA', 'position' => 'COORDINADOR COMERCIAL', 'salary' => 2843203, 'area_id' => 3]);
        employee::create(['document' => 31642277, 'name' => 'FERNANDEZ ESCOBAR ISABEL JULIANA', 'position' => 'DIRECTOR DE GESTION HUMANA', 'salary' => 5504973, 'area_id' => 4]);
        employee::create(['document' => 31948988, 'name' => 'ASPRILLA MORENO HERLINDA', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 38466382, 'name' => 'ALEGRIA GARCIA LUZ ADRIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 38469388, 'name' => 'RIASCO RIASCO MARISELLA', 'position' => 'AUXILIAR DE ARCHIVO', 'salary' => 1300000, 'area_id' => 4]);
        employee::create(['document' => 38469895, 'name' => 'VELASCO OLAYA MARICEL', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 38472530, 'name' => 'GUZMAN JIMENEZ SUSY JULIANA', 'position' => 'ASESORES DE VENTA', 'salary' => 1, 'area_id' => 3]);
        employee::create(['document' => 39322047, 'name' => 'GONZALEZ VIANA BIBIANA', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1441531, 'area_id' => 3]);
        employee::create(['document' => 6162184, 'name' => 'CASIERRA PEREA MANUEL', 'position' => 'COORDINADOR DE SOPORTE TECNICO', 'salary' => 2096553, 'area_id' => 1]);
        employee::create(['document' => 6162211, 'name' => 'DIAZ RIASCOS JOHN JAIRO', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1575305, 'area_id' => 3]);
        employee::create(['document' => 6162996, 'name' => 'ZULUAGA ACEVEDO FREDERMAN', 'position' => 'AUXILIAR DE SISTEMA DE GESTION  SST', 'salary' => 1160000, 'area_id' => 4]);
        employee::create(['document' => 66733841, 'name' => 'HINESTROZA HERRERA NUBIA', 'position' => 'CONSERJE SERVICIOS GENERALES', 'salary' => 1300000, 'area_id' => 8]);
        employee::create(['document' => 66742130, 'name' => 'LOAIZA MOSQUERA MARIA SONIA', 'position' => 'COORDINADOR DE SALUD OCUPACIONAL Y BIENESTAR SOCIA', 'salary' => 2881070, 'area_id' => 4]);
        employee::create(['document' => 66743652, 'name' => 'CABEZAS CASQUETE LIDA EMILSEN', 'position' => 'ANALISTA DE NOMINA', 'salary' => 1967040, 'area_id' => 4]);
        employee::create(['document' => 66747527, 'name' => 'VALDEZ TENORIO ROSA ELENA', 'position' => 'ASESORES DE VENTA', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 67025504, 'name' => 'HUAZA CONGO MARTHA ISABEL', 'position' => 'ASISTENTE DE CALIDAD', 'salary' => 1467990, 'area_id' => 4]);
        employee::create(['document' => 94269828, 'name' => 'MUÑOZ GARCES OSCAR IVAN', 'position' => 'ESCOLTA', 'salary' => 1816704, 'area_id' => 2]);
        employee::create(['document' => 94419424, 'name' => 'ROJAS LOPEZ EDUARD', 'position' => 'COORDINADOR DE ZONA', 'salary' => 2732000, 'area_id' => 3]);
        employee::create(['document' => 94420694, 'name' => 'CLAVIJO JAVIER', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1300000, 'area_id' => 3]);
        employee::create(['document' => 94421510, 'name' => 'MARTINEZ MOSQUERA ALVARO JOHAN', 'position' => 'OPERADOR DE MEDIOS TECNOLOGICOS', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94421558, 'name' => 'OBANDO COLLAZOS HECTOR FABIO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94422854, 'name' => 'HENAO MORALES EMERSON', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94423207, 'name' => 'GALLEGO GOMEZ CHRISTIAN CAMILO', 'position' => 'AUXILIAR SOPORTE TECNICO', 'salary' => 1300000, 'area_id' => 1]);
        employee::create(['document' => 94439891, 'name' => 'RUIZ OBREGON LUIS ALBERTO', 'position' => 'VIGILANTE', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94443260, 'name' => 'ALOMIA PEREA OSWALDO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94444564, 'name' => 'MINA TOVAR JAVIER MAURICIO', 'position' => 'GUARDA DE SEGURIDAD', 'salary' => 1300000, 'area_id' => 2]);
        employee::create(['document' => 94445436, 'name' => 'VILLEGAS ANGULO RONALD ANDRES', 'position' => 'SUPERVISOR DE VENTAS', 'salary' => 1441531, 'area_id' => 3]);
        employee::create(['document' => 94497055, 'name' => 'GOMEZ BEJARANO CARLOS JAVIER', 'position' => 'IMPULSADOR DE PRODUCTOS DE JUEGOS DE SUERTE Y DERI', 'salary' => 1160000, 'area_id' => 3]);
        employee::create(['document' => 9801323, 'name' => 'ZAPATA ECHEVERRY CARLOS ALBERTO', 'position' => 'SUPERVISOR DE SEGURIDAD', 'salary' => 2408531, 'area_id' => 2]);
        // employee::create(['document' =>1005869928     ,'name' =>'FREYDE SINISTERRA ANA MICHEL','position' =>'ANALISTA DE DATOS','salary' =>1300000,'area_id' =>3]);

    }
}
